config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  devise_for :users
  root to: 'blogs#index'
  resources :blogs do
    collection do
      get 'today'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user

  validates :title,      presence: true
  validates :start_time, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs

  validates :name, presence: true

  VALID_PASSWORD_REGEX = /\A[a-z0-9]+\z/i
  validates :password, format: { with: VALID_PASSWORD_REGEX }

  def self.guest
    find_or_create_by!(email: 'test@example.com') do |user|
      user.password = examplepassword
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!
  before_action :move_to_index, only: [:edit, :show, :destroy]

  def index
      @blogs = Blog.all
      @blog = Blog.new
  end
  
  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(blog_parameter)
    if @blog.save
      redirect_to blogs_path
    else
      redirect_to root_path
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, notice:"削除しました"
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_parameter)
      redirect_to blogs_path, notice: "編集しました"
    else
      render 'edit'
    end
  end


  def today
    @blogs = Blog.where( start_time: Date.today .. Date.tomorrow)
  end

  private

  def blog_parameter
    params.require(:blog).permit(:title, :content, :start_time).merge(user_id: current_user.id)
  end

  def move_to_index
    blog = Blog.find(params[:id])
    redirect_to action: :index if blog.user_id != current_user.id
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < ApplicationController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/views/blogs/edit.html.erb
<%= render "shared/header" %>

<%= form_with(model: @blog, local: true) do |form| %>

<p class="edit-text">編集</p>

<p class="form-tag1">タイトル</div>
<div class="title-field"><%= form.text_field :title,  class:"form-tag-box"%></div>




<div class="form-tag2">内容</div>
<div class="content-field"><%= form.text_field :content,  class:"content-box" %></div>
  

    
<div class="form-tag3">時間</div>
<div class="time-field"><%= form.datetime_select :start_time%></div>
  


  <div class="submit-field">
    <%= form.submit class:"submit-box" %>
  </div>

<% end %>

<%= render "shared/footer" %>

app/views/blogs/index.html.erb
<%= render "shared/header" %>
<div class="toppage">
<h1 class="top"></h1>
<br>

<div class="row">
<div class="col-md-4">
	<div class="schedule">今後の予定一覧</div>
<table class="table">
  <thead class="thead-light">
    <tr class="border">
      <th class="border"><p class="border-text">タイトル</p></th>
      <th class="border"><p class="border-text">日程</p></th>
    </tr>
  </thead>


    <tbody>
      <% @blogs.each do |blog| %>
        <% if current_user.id == blog.user_id %>
          <tr>
            <td><%= link_to blog.title , blog %></td>
            <td><%= blog.start_time.strftime("%m月 %d日") %></td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
</table>



<%= form_with(model: @blog, local: true) do |form| %>

  <div class="title">
    <div class="form-tag">タイトル  <span class="title-hissu">(必須)</span></div>
    <%= form.text_field :title,  class:"form-tag-box"%>
  </div>


  <div class="content">
    <div class="form-tag">内容</div>
    <%= form.text_field :content,  class:"content-box"%>
  </div>

    <div class="time">
    <div class="form-tag form-tag-time">時間</div>
    <%= form.datetime_select :start_time, class:"time-box" %>
  </div>

 <div class="submit">
    <%= form.submit class:"submit-box"%>
 </div>
 <li class="index-error-messages"><%= render 'layouts/error_messages', model: form.object %></li>
<% end %>
</div>

<br>


<br>
<div class="col-md-8">
 <p class="user-calendar"><%= current_user.name %>さんのカレンダー</p> 
<%= month_calendar events: @blogs do |date, blogs| %>
  <%= date.day %>
    <% blogs.each do |blog| %>
      <% if current_user.id == blog.user_id %>
        <div>
          <%= link_to blog.title, blog %>
        </div>
      <% end %>
    <% end %>
<% end %>
</div>
</div>
</div>

<%= render "shared/footer" %>

app/views/blogs/show.html.erb
<%= render "shared/header" %>

<p class="showsai">予定詳細</p>
<p class="title-text">タイトル：</p>
<div class="title-box">
  <p class="blog-title"><%= @blog.title %></p>
</div>



<p class="naiyou-text">内　　容：</p>
<div class="naiyou-box">
  <p class="blog-naiyou"><%= simple_format(@blog.content) %></p>
</div>




<p class="nitizi-text">日　　時：</p>
<div class="nitizi-box">
  <%= @blog.start_time.strftime("%Y年%m月%d日%H時%M分") %>
</div>



<%= link_to '編集', edit_blog_path(@blog), class: "edit-btn" %>
<%= link_to '削除',blog_path(@blog.id), class: "destroy-btn", method: :delete, data: { confirm: '本当に?' } %>
<%= link_to '戻る', blogs_path, class: "back-btn" %>


<%= render "shared/footer" %>

app/views/blogs/today.html.erb
<%= render "shared/header" %>

<div class="today-task"><%= Date.current.strftime("%m月 %d日") %>の予定</div>

<div class="today-blog">
      <% @blogs.each do |blog| %>
        <% if current_user.id  == blog.user_id  %>
            <tr class="today-plan">
              <td ><%= link_to blog.title, blog %></td>
              <td><%= blog.start_time.strftime("%H時%M分") %></td>
            </tr>
        <% end %>
      <% end %>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timeplan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Bangers rel="stylesheet">
    <!-- lessファイルを読み込みます -->
    <link rel="stylesheet/less" type="text/css" href="less/styles.less" />
    <!-- lessファイルを解釈するJSを読み込みます -->
    <script type="text/javascript" src="js/less-1.3.3.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer>
  <p>©2022     TimePlan</p>
</footer>

app/views/shared/_header.html.erb
<header>
    <div class="header-logo">
    <%= link_to image_tag("logo.png", class:"header-logo"), "/" %>
  </div>
  <div class="TimePlan">
    <%= link_to  root_path, class: "TimePlan-link" do %>
      <span class="span1">Time</span><span class="span2">Plan</span>
    <% end %>
  </div>
    <%= link_to 'カレンダー', root_path, class: "header-calender" %>
    <%= link_to 'Today', today_blogs_path, class: "ToDo" %>
    <%= link_to 'ログアウト', destroy_user_session_path,  method: :delete, class: "logout" %>
</header>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>